### ISSUE TITLE
JsonInclude.Include.NON_EMPTY does not replace deprecated WRITE_EMPTY_JSON_ARRAYS

### ISSUE THREAD

**Issue by rpatrick00** [FasterXML/jackson-annotations#102]
In moving from Jackson 2.7.6 to 2.8.3, we are now getting compiler warnings with regards to our use of the SerializationFeature.WRITE_EMPTY_JSON_ARRAYS.  From what I can tell, the recommendation is to replace this with JsonInclude.Include.NON_EMPTY.

Our code previously looked like this:

    public static ObjectMapper getJacksonObjectMapper() {
        ObjectMapper mapper = new ObjectMapper();
        mapper.configure(SerializationFeature.INDENT_OUTPUT, true);
        mapper.configure(SerializationFeature.FAIL_ON_EMPTY_BEANS, false);
        mapper.configure(SerializationFeature.WRITE_EMPTY_JSON_ARRAYS, false);
        mapper.setSerializationInclusion(JsonInclude.Include.NON_EMPTY);
        return mapper;
    }

and when serializing JSON, empty arrays are omitted.  

If I comment out the deprecated WRITE_EMPTY_JSON_ARRAYS line, and write the exact same object, the JSON has empty array elements within it.

Here is a simple test case, just unzip and run mvn package and look at the test output and you will see something that looks like the following:

Running test.EmptyArraysTest

Printing object with WRITE_EMPTY_JSON_ARRAYS set to false:

{
  "id" : "123"
}

Printing object without WRITE_EMPTY_JSON_ARRAYS:

{
  "id" : "123",
  "databases" : [ ]
}

What am I missing?  
[jackson-empty-arrays-test.zip](https://github.com/FasterXML/jackson-annotations/files/494425/jackson-empty-arrays-test.zip)

**Comment by cowtowncoder** [comment]
@rpatrick00  The problem here is that `MyClass` has override for `@JsonInclude`:

    @JsonInclude(JsonInclude.Include.NON_NULL)

which will only suppress writing of `null`s; since it is more specific than global defaults it will have precedence.

Another thing to note on replacement is that in addition to global inclusion default, and per-property annotation (that is, can put `@JsonInclude` on field/setter/getter), with 2.8 you can also specify type defaults:

```java
        mapper.configOverride(Map.class)
            .setInclude(JsonInclude.Value.construct(JsonInclude.Include.NON_EMPTY, null));
```

which should then make all `List<>` valued properties default to excluding empty, as well as null, values.

**Comment by rpatrick00** [comment]
As you can see, I have no control over the class- and field-level annotations since they are generated by another tool.  I am looking for a replacement for:

mapper.configure(SerializationFeature.WRITE_EMPTY_JSON_ARRAYS, false);

Nothing you are describing seems to replace that functionality when I have no control over the annotated classes.  What am I missing?

**Comment by cowtowncoder** [comment]
@rpatrick00 perhaps reading my answer completely?

**Comment by rpatrick00** [comment]
I read and tried your suggestion and it doesn't work...

[jackson-empty-arrays-test-v2.zip](https://github.com/FasterXML/jackson-annotations/files/499280/jackson-empty-arrays-test-v2.zip)

**Comment by shollander** [comment]
@cowtowncoder I have the same issue and I am looking for a good solution. Unfortunately, using `configOverride` does not provide the same functionality as `WRITE_EMPTY_JSON_ARRAYS` since configOverride requires the class to be specified. 

This does not work with arrays since arrays can be of any type. I tried using `Object[].class` but that does not match on other types.

This also does not work well with Collections. I tried using `Collection.class` but that does not match if the declared type is some other type that implements Collections.

So in order to replace the one line `mapper.configure(SerializationFeature.WRITE_EMPTY_JSON_ARRAYS, false);` I would need to specify every implementation of Collection and that still wouldn't work for arrays in a generic manner.

I cases where one has control over the class then annotations can work, but many times that is not an option. Even in cases where it is an option it can be much more cumbersome to start annotation every affected class and field instead of one line ObjectMapper configuration. 

It would be nice if there was a good replacement for WRITE_EMPTY_JSON_ARRAYS that preserved the original functionality.

**Comment by cowtowncoder** [comment]
@shollander First of all, yes, I think your assessment on how things work, limitations, is correct.

Unfortunately this feature is bit difficult in terms of making work with the configuration system, due to couple of reasons:

1. As `SerializationFeature`, it should be possible to enable/disable on per-call basis: this is different how inclusion functionality in general works. While there are exceptions (and I believe it doesn't actually allow such changing), this would make it more a `MapperFeature`
2. Since there is no way (currently) to have third choice ("use defaults"), there is no good way to necessarily know full intent of user.

... put another way, it was added earlier, to solve one problem, but does not fit very well with later designs, from internal/implementation perspective.

At the same time, I see the challenge you may have. I am not sure how this can be resolved; as this almost feels like something that should be handled at lower level by `JsonGenerator` (by suppressing any empty JSON Arrays). This would be more reliable as it would work for any serializer.
Then again this could be problematic in detecting intent wrt arrays in arrays.

Now: it might help if I understood bit more about what you want to achieve: is this to reduce size of content? Are you only expecting it to suppress empty arrays for property values?

**Comment by cowtowncoder** [comment]
@shollander Created https://github.com/FasterXML/jackson-databind/issues/1547 to track this.

**Comment by shollander** [comment]
@cowtowncoder Thank you for considering this issue. As far as answering your question, I am maintaining someone else's code to I am not 100% sure of what they wanted to achieve. I would assume it is to reduce the size of the generated json as you surmised. I am not sure what you mean by

> Are you only expecting it to suppress empty arrays for property values?

**Comment by cowtowncoder** [comment]
@shollander Understood; if you didn't write it it's difficult to know goals. My assumption so far has been that it's mostly optimization, removing defaults and such. But I know that I have often missed alternate use cases.

**Comment by jlous** [comment]
In my case the need stemmed from wanting to please a consumer with the format they preferred from their custom REST endpoint, without needing to alter the internal document model used across the solution, including persisted JSON.

**Comment by cowtowncoder** [comment]
Quick note here: if anyone wants to re-open the feature request, please do so at `jackson-databind` as Annotations package only deals with definition of annotations themselves and not any logic taken on them. If filing a new one (I'd rather do that than transfer this one), you can add reference this issue as background, but please summarize how "config overrides" is not workable solution.
