### ISSUE TITLE
Add `@JsonFormat.lenient` to allow configuring lenience of date/time deserializers

### ISSUE THREAD

**Issue by chrisbloe** [FasterXML/jackson-annotations#105]
When I specify a date in the form:
`@JsonFormat(pattern = "yyyy-MM-dd") Date endDate;`
I would like to set the leniency to false.

Currently, a value of 2016-225-35 is allowed, but I would like to make this invalid.

e.g.
`@JsonFormat(pattern = "yyyy-MM-dd", lenient = false) Date endDate;`

**Comment by cowtowncoder** [comment]
Hmmh. This is tricky... leniency is such a `java.util.Date` (or, related date format) specific thing that it doesn't necessarily fit well with general-purpose annotations. But maybe it'd be possible to add some sort of extension mechanism that specific datatype (de)serializers could use.

**Comment by chrisbloe** [comment]
Thanks for the quick reply :)

I thought this too, but there is already a timezone parameter, which is also Date specific? It's a shame there's no character that can be used in the pattern string that denotes leniency.

**Comment by cowtowncoder** [comment]
True, `timezone` is indeed rather date/time specific; although unlike leniency covers multiple date/time libs.

Although come to think of that, general concept of leniency might actually be relevant for other types as well. So perhaps this is something that should be added for 2.9 (needs to be there since it's an API change; plus annotation packages never change in patch versions).

**Comment by cowtowncoder** [comment]
Added annotation; need to add issue for databind to actually make use of it.
