### ISSUE TITLE
@JsonAnyGetter can't be used on fields, even though documentation says it can be and @JsonAnySetter can

### ISSUE THREAD

**Issue by Raniz85** [FasterXML/jackson-annotations#107]
The documentation for [JsonAnyGetter](http://fasterxml.github.io/jackson-annotations/javadoc/2.8/) states that it can be used on fields (emphasis mine):

> Marker annotation that can be used to define a non-static, no-argument method or member **field** as something of a reverse of JsonAnySetter method

But the [code](https://github.com/FasterXML/jackson-annotations/blob/5e34d4bca114106f7c14081b6efac7bdb0045dbf/src/main/java/com/fasterxml/jackson/annotation/JsonAnyGetter.java) only includes *ANNOTATION_TYPE* and *METHOD*.

`@JsonAnySetter` however also includes *FIELD* (but doesn't mention that this is valid in the documentation).

**Comment by cowtowncoder** [comment]
Agreed: should improve handling (and javadocs for `@JsonAnySetter` -- this was implemented via #1047 for 2.8 and javadocs were not improved).
I created

https://github.com/FasterXML/jackson-databind/issues/1458

since there's some work on databind to make this possible, not just annotations (since access from fields differs from methods).

Thank you for reporting this; hoping to implement for 2.9!

**Comment by cowtowncoder** [comment]
Javadocs updated to reflect actual implementation. Also note somewhat related issue #109 which allows disabling of effects of both annotations (usually using mix-in annotations).

Note that if ability to annotate fields as "any getters" is desired, a new issue may be filed (similar to how support for "any setter" side was added).
