### ISSUE TITLE
Intermitten JsonParseException and JsonMappingException

### ISSUE THREAD

**Issue by vivekgurukul1982** [FasterXML/jackson-annotations#115]
Hi - I am getting the below exceptions when I am giving more than 2 JSON messages in JSON array, Code is working fine with 1 or 2 JSON messages in JSON Array, Is it known bug? if not how to handle this in deserialization code? FYI - The below exceptions are intermittent and not every time so really getting frustrated to get rid of these annoying errors.

com.fasterxml.jackson.core.JsonParseException: Unexpected end-of-input within/between Array entries
 at [Source: [B@43fd9452; line: 1, column: 5313]

com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.ArrayList out of START_OBJECT token

**Comment by cowtowncoder** [comment]
This is not related to Jackson annotations in any way, so it should be filed under `jackson-databind`.
Listing symptoms does not allow determination whether this would be a bug: what is needed (as per mailing group response) code to reproduce the issue you see, including JSON content being read.
Finally you need to also include version of Jackson: and ideally before filing an issue you should try at least latest patch version of the minor version (for example, instead of filing for `2.4.1`, first upgrade to `2.4.6` which is fully compatible but has many bug fixes applied; one if which might address issue you are seeing).
