### ISSUE TITLE
publish 3.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-annotations#163]
Would it be possible to publish a 3.0.0-SNAPSHOT?

https://oss.sonatype.org/content/repositories/snapshots/com/fasterxml/jackson/core/jackson-annotations/

This has 3.0-SNAPSHOT but for version consistency it would ideally be 3.0.0-SNAPSHOT.

**Comment by cowtowncoder** [comment]
Versioning will change with 3.x, so there will not be 3.0.0 -- it will be 3.0, 3.1 and so forth (although in rare critical circumstances it might be necessary to have something like 3.1.1).
So for dependencies, please use 3.0-SNAPSHOT, or just use transitive version via `jackson-databind` (or `jackson-bom`).

This because there should never be any changes introduced in annotation definitions in patches; this is something that 2.x has done. But keeping patch indicator confuses users so it seems better to get rid of it.

Consistency across components can still be achieved via `jackson-bom` (for alignment), which uses full patch version scheme; but individual components will also define their requirements.

**Comment by pjfanning** [comment]
Thanks for the explanation. I will remove the explicit dependency on jackson-annotations and get it transitively via jackson-databind.

**Comment by cowtowncoder** [comment]
Np. At some point I need to document changes better -- this is one of more visible ones anyway.
