### ISSUE TITLE
A  interface has annodationed (@JsonTypeInfo/@JsonSubTypes) , but got a Exception

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [FasterXML/jackson-annotations#208]
version: 2.13.3 
``` java
  class Test {

    private List<IDemo> configItems;
private String name;
}
```
```java
  objectMapper.readValue(sysConfig.getValue(), new TypeReference<T>() {
        });
```

``` java 
 // on the IDemo interface  already define annodations
 @JsonTypeInfo(use = JsonTypeInfo.Id.NAME,  property = "type")
  @JsonSubTypes({
            @JsonSubTypes.Type(Demo1.class),
            @JsonSubTypes.Type(Demo2.class)
    })
```
 
why i got a exception:
```
 class java.util.LinkedHashMap cannot be cast to class
```

How can i do to resolve this exception？？

**Comment by cowtowncoder** [comment]
Because you `T` is an unbound type variable. You cannot use those. Instead you need to use something like

```
new TypeReference<List<IDemo>>() { }
```

or whatever target type you want.

Or if you just want deserialize `Test` pass `Test.class` instead of `TypeReference`.

Going forward please use mailing list or chat:

* https://groups.google.com/g/jackson-user
* https://gitter.im/FasterXML/jackson-databind

for usage questions; issue tracker is for reporting problems and requesting new features.
