### ISSUE TITLE
Annotation for DeserializationConfig.Feature ACCEPT_SINGLE_VALUE_AS_ARRAY (via @JsonFormat(with=Feature.ACCEPT_SINGLE_VALUE_AS_ARRAY))

### ISSUE THREAD

**Issue by Polve** [FasterXML/jackson-annotations#43]
I would like to configure that property per-class, using annotations.

**Comment by cowtowncoder** [comment]
Note: will be implemented as somewhat general-purpose facility, extension to `@JsonFormat` with new properties `with` and `without`, and enumeration `JsonFormat.Feature` that defines possible features to enable/disable. The reason latter is needed (instead of referring to `SerializationFeature`, `DeserializationFeature`) is that annotation package does not (and can not) depend on `jackson-databind`, so there will be bit of redundancy. On plus side this does allow carefully selecting kinds of features that can and should be supported, as well as possibly adding things for which there is no databind-level feature.

**Comment by fabiolaa** [comment]
This was a nice addition. I encountered a possible problem: #67
