### ISSUE TITLE
Ignoring all properties but a few

### ISSUE THREAD

**Issue by jmcazaux** [FasterXML/jackson-annotations#81]
Hi there,
I do have a pretty hefty Java class (bad design, but lets not go there) and I'd like to serialise only 2 or three of it properties.

how can I do this ? Basically, I am looking for "ignore all but e few" behaviour.

I have added: 
`@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.NONE, getterVisibility = JsonAutoDetect.Visibility.NONE, setterVisibility = JsonAutoDetect.Visibility.NONE)`
just above the class declaration so that it does not auto detect anything, but now how can I force the 2 or there properties I need ?

I tried adding a @JsonProperty above those properties, but it would not work (it generated an empty JSON).

Many thanks in advance,
JM

**Comment by cowtowncoder** [comment]
In general, mailing lists are GREAT for questions. Much better than issue trackers.

But I think I can see an RFE within question here: I think you are asking for "like `@JsonIgnoreProperties` but reverse, like `@JsonInferProperties`"?

If so, no such functionality yet exists. I think that would make sense, but the way things work it is not trivial to achieve.

**Comment by jmcazaux** [comment]
@cowtowncoder sorry for posting in the wrong place. I am even more confused as I used the ML in the past, don't know why it did not cross my mind now.

Thanks for the clarification.
I think my best option is to use a downsized version of my class with just the necessary properties.
That will be much cleaner than adding `@JsonIgnoreProperties` on 98% on the properties.

**Comment by cowtowncoder** [comment]
@jmcazaux yeah no prob; as I said, this qualifies as an RFE of its own. I just like to mention ML since not all devs are aware it exists (and I'm bad with names, apologies if/when we are exchanged notes before :) ).

And yes, for now that may work best. There are other ways f.ex. by sub-classing `JacksonAnnotationIntrospector` to implement custom handling for auto-detecting properties, perhaps using your own annotations. But it may not be simpler thing to do in the end.
