### ISSUE TITLE
Polymorphic Serialization issue with google AutoValue

### ISSUE THREAD

**Issue by nlenoire** [FasterXML/jackson-annotations#88]
Hi,

I'm using google AutoValue to implement POJOs I want to serialize using Jackson. Some of my POJOs are using polymorphism. For them, I'm using the JsonTypeInfo + JsonSubTypes annotation with a property as type info. 

However, Jackson ignores the type name I set, and always use the class name as class indicator. I can workaround this issue by using @JsonTypeName on each of my sub-types, but I don't like this since I'm required to squatter the JSON ser/deser configuration.

Here is an example:
```java
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type")
@JsonSubTypes({
	@JsonSubTypes.Type(value = ConcreteType1.class, name = "type1"),
	@JsonSubTypes.Type(value = ConcreteType2.class, name = "type2")
})
static interface AbstractType {
		
}
	
@AutoValue
static abstract class ConcreteType1 implements AbstractType {
		
	public static ConcreteType1 create(String value) {
		return new AutoValue_ConcreteType(value);
	}
				
	public abstract String getMyProperty();
}

...
```
```java
new ObjectMapper().writeValueAsString(ConcreteType1.create("aValue"));
```
will produce

```
{
   "type": "AutoValue_ConcreteType1",
   "myProperty": "aValue"
}
```
instead of

```
{
   "type": "type1",
   "myProperty": "aValue"
}
```
Is it a bug ? Am I doing something wrong ?

Thanks,

**Comment by cowtowncoder** [comment]
Usage looks good, but doesn't AutoValue actually generate impl classes? If so, the problem is that your associate only goes to abstract class, and not implementation.
You may be better off using `@JsonTypeName` annotation, which should be inherited.

This is an interesting problem and I am not sure how to improve non-annotation handling. It would be nice to be able to use mechanism as you try to, but I am not sure if or how that could be implemented.
It could perhaps be possible to implement AutoValueModule which could implementation `AnnotationIntrospector` that can take into account additional data AutoValue library exposes (if it does), if anyone was interested in pursuing this further.

**Comment by nlenoire** [comment]
Independently of AutoValue, does it means that Mixins, that are abstract classes, cannot use the @JsonSubTypes.Type with the name type indicator?

**Comment by cowtowncoder** [comment]
@nlenoire Mix-ins work just fine, but `@JsonSubTypes` point to exact class, not to potential basetypes. That is, if you have inheritance hierarchy of 3 types:

* `Base`
* `Intermediate extends Base`
* `Impl extends Intermediate`

it is not sufficient for `Base` to have `@JsonSubTypes` that points to `Intermediate`; this does not lead to `Impl` having type id.

I also now noticed location of this issue; it belongs under `jackson-databind`, as this package only defines annotations, but not how they are handled.

**Comment by nlenoire** [comment]
@cowtowncoder I will create an issue under `jackson-databind` for this problem. Thanks!
